name: ms持续集成

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - name: 检出仓库代码
      uses: actions/checkout@master
      
    - name: 安装Node.js 14.x
      uses: actions/setup-node@master
      with:
        node-version: "14.x"
    
    - name: 安装依赖
      run: |
        npm install

    - name: 构建
      run: |
        npm run build

    - name: 上传artifact
      uses: actions/upload-artifact@v3
      with:
        name: ms-dist
        path: dist
        retention-days: 1

  # deploy-page:
  #   runs-on: ubuntu-latest
  #   needs: build
        
  #   steps:
  #   - name: 下载构建结果
  #     uses: actions/download-artifact@v3
  #     with:
  #       name: ms-dist
  #       path: ms-dist

  #   - name: 部署到Pages
  #     uses: s0/git-publish-subdir-action@develop
  #     env:
  #       REPO: git@github.com:ms/ms.github.io.git
  #       BRANCH: main
  #       FOLDER: ms-dist
  #       SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}

  deploy-tx:
    runs-on: ubuntu-latest
    environment: 
      name: TencentCOS
    needs: build
        
    steps:
    - name: 下载构建结果
      uses: actions/download-artifact@v3
      with:
        name: ms-dist
        path: ms-dist

    - name: Upload COS
      uses: zkqiang/tencent-cos-action@v0.1.0
      with:
        args: upload -rfs --delete ./ms-dist/ /
        secret_id: ${{ secrets.TCLOUD_API_ID }}
        secret_key: ${{ secrets.TCLOUD_API_KEY }}
        bucket: ms-1252906577
        region: ap-beijing


  deploy-gh-page:
    runs-on: ubuntu-latest
    environment: 
      name: TencentCOS
    needs: build
    steps:
    - name: 下载构建结果
      uses: actions/download-artifact@v3
      with:
        name: ms-dist
        path: ms-dist

    - name: 部署
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: ms-dist
