name: ms持续集成

on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: 
      name: TencentCOS
        
    steps:
    - name: 检出仓库代码
      uses: actions/checkout@master
      
    - name: 安装Node.js 14.x
      uses: actions/setup-node@master
      with:
        node-version: "14.x"
    
    - name: 安装依赖
      run: |
        npm install

    - name: 构建
      run: |
        npm run build

    - name: 部署pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist

    - name: 上传腾讯云COS
      uses: zkqiang/tencent-cos-action@v0.1.0
      with:
        args: upload -rfs --delete ./dist/ /
        secret_id: ${{ secrets.TCLOUD_API_ID }}
        secret_key: ${{ secrets.TCLOUD_API_KEY }}
        bucket: ms-1252906577
        region: ap-beijing
